const PDF_TEMPLATES = {
  professional: (title, content, iconBase64, metadata = {}) => `
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px 50px 80px; color: #1a1a1a; line-height: 1.7; background: #fff; }
          .header { display: flex; align-items: center; justify-content: space-between; padding-bottom: 16px; margin-bottom: 24px; border-bottom: 1px solid #eee; }
          .brand { display: flex; align-items: center; gap: 10px; font-size: 0.95rem; font-weight: 600; color: #333; }
          .brand img { width: 28px; height: 28px; object-fit: contain; }
          .date { font-size: 0.75rem; color: #999; }
          h1 { font-size: 1.8rem; font-weight: 700; margin-bottom: 24px; color: #111; line-height: 1.3; }
          h2 { font-size: 1.3rem; font-weight: 600; margin: 28px 0 10px; color: #222; }
          h3 { font-size: 1rem; font-weight: 600; margin: 20px 0 8px; color: #444; }
          p { margin-bottom: 14px; font-size: 0.95rem; }
          table { border-collapse: collapse; width: 100%; margin: 20px 0; font-size: 0.9rem; }
          th { background: #f5f5f5; padding: 10px 14px; text-align: left; font-weight: 600; border-bottom: 2px solid #ddd; }
          td { padding: 8px 14px; border-bottom: 1px solid #eee; }
          blockquote { border-left: 3px solid #ccc; padding: 10px 18px; color: #555; margin: 16px 0; font-style: italic; }
          code { background: #f4f4f4; padding: 2px 5px; border-radius: 3px; font-size: 0.88em; }
          pre { background: #1a1a2e; color: #e0e0e0; padding: 16px; overflow-x: auto; margin: 20px 0; border-radius: 6px; white-space: pre-wrap; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; display: flex; justify-content: space-between; font-size: 0.75rem; color: #aaa; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="brand">${iconBase64 ? `<img src="${iconBase64}" alt="Aartiq" />` : ''} Aartiq Browser</div>
          <div class="date">${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
        </div>
        <h1>${title}</h1>
        <div>${content}</div>
        <div class="footer">
          <span>${iconBase64 ? `<img src="${iconBase64}" style="width:14px;height:14px;vertical-align:middle;margin-right:4px;" />` : ''} Generated by Aartiq Browser</span>
          <span>${title}</span>
        </div>
      </body>
    </html>
  `
};

function parseMarkdownTables(content) {
  const tableRegex = /\|(.+)\|\n\|[-:\s|]+\|\n((?:\|.+\|\n?)+)/g;
  return content.replace(tableRegex, (match, headerRow, bodyRows) => {
    const headers = headerRow.split('|').map(h => h.trim()).filter(h => h);
    const rows = bodyRows.trim().split('\n').map(row =>
      row.split('|').map(cell => cell.trim()).filter(c => c)
    );

    let html = '<div class="table-wrapper"><table><thead><tr>';
    headers.forEach(h => { html += `<th>${h}</th>`; });
    html += '</tr></thead><tbody>';
    rows.forEach(row => {
      html += '<tr>';
      row.forEach(cell => { html += `<td>${cell}</td>`; });
      html += '</tr>';
    });
    html += '</tbody></table></div>';
    return html;
  });
}

function parseMarkdownToHTML(content) {
  let html = content;
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');
  html = html.replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>');
  html = html.replace(/^---$/gm, '<hr/>');
  return html;
}

function generateAartiqPDFTemplate(title, content, iconBase64, metadata = {}) {
  const isFullHTML = /<html/i.test(content);
  if (isFullHTML) return content;

  let cleanContent = content
    .replace(/\[WATERMARK:\s*([^\]]+)\]/gi, (_, w) => { metadata.watermark = w; return ''; })
    .replace(/\[TEMPLATE:\s*([^\]]+)\]/gi, () => '');

  cleanContent = parseMarkdownTables(cleanContent);
  cleanContent = parseMarkdownToHTML(cleanContent);

  return PDF_TEMPLATES.professional(title, cleanContent, iconBase64, metadata);
}

module.exports = {
  generateAartiqPDFTemplate,
  parseMarkdownTables,
  parseMarkdownToHTML
};
